apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
 name: tanzu-tap-repository
spec:
 fetch:
   imgpkgBundle:
     image: registry.pivotal.io/tanzu-application-platform/tap-packages:0.1.0
     secretRef:
       name: tap-registry