apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app-name
  labels:
    app.tanzu.vmware.com/workload-type: web   # (1)

spec:
  source:
    git:
      url: git-repo
      ref:
        branch: "main"
        #tag: "v0.0.1"
        #commit: "b4df00d"
  services:
    - apiVersion: services.tanzu.vmware.com/v1alpha1
      kind: db-type

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m

  params:
    - name: my-company.com/defaults/java-version
      value: 11
    - name: debug
      value: true