# this is a mockup file to illustrate future AppStack concepts 
apiVersion: experimental.kontinue.io/v1
kind: Workload
metadata:
  name: dekt4pets-workflow
  labels:
    app.kubernetes.io/name: dekt4pets-workflow
    app.tanzu.vmware.com/workload-type: supplychain
  spec:
    components:
      - name: source-provider
        templateRef:
          kind: SourceTemplate
          name: git-repository-battery
      - name: build-image-provider
        templateRef:
          kind: BuildTemplate
          name: kpack-battery
      - name: api-microservices-workflow
        templateRef:
          kind: OpinionTemplate
          name: pipeline-battery
